language: rust
dist: trusty
sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-gfx-dev
rust:
  - stable
branches:
  only:
  - master
