[package]
authors = ["Weston Carlson <wez470@gmail.com>"]
name = "rustboy"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1.0.4"
clap = "2.32.0"
rand = "0.6.4"
sdl2 = "0.32.1"
log = "0.4.6"
env_logger = "0.6.0"

[dev-dependencies]
quickcheck = "0.8.0"

[profile.release]
debug = true
