[package]
authors = ["Weston Carlson <wez470@gmail.com>"]
name = "rustboy"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "0.8.0"
clap = "2.19.0"
rand = "0.3.15"
sdl2 = "0.29.1"

[dev-dependencies]
quickcheck = "0.4.1"

[profile.release]
debug = true
